# Generated by Django 3.1.4 on 2021-01-12 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
